# Generated by Django 3.1.2 on 2020-10-18 08:10

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('poultry_type', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('eggs_year', models.IntegerField(blank=True, max_length=50, null=True)),
                ('adult_weight', models.FloatField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('front_photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='breed_photos')),
                ('side_photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='breed_photos')),
                ('back_photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='breed_photos')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breed',
                'db_table': 'breed',
                'ordering': ['created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Breeders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('hens', models.IntegerField(blank=True, max_length=50, null=True)),
                ('cocks', models.IntegerField(blank=True, max_length=50, null=True)),
                ('mortality', models.FloatField(blank=True, max_length=50, null=True)),
                ('butchered', models.IntegerField(blank=True, max_length=50, null=True)),
                ('sold', models.IntegerField(blank=True, max_length=50, null=True)),
                ('current_number', models.IntegerField(blank=True, max_length=50, null=True)),
                ('hens_photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='breeders_photos')),
                ('cocks_photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='breeders_photos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeders_breed', to='breeders.breed')),
            ],
            options={
                'verbose_name': 'Breeders',
                'verbose_name_plural': 'Breeders',
                'db_table': 'breeders',
                'ordering': ['created'],
                'managed': True,
            },
        ),
    ]
