# Generated by Django 3.1.2 on 2020-10-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chicks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batchnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.DateField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breed_chicks', to='breeders.breed')),
            ],
            options={
                'verbose_name': 'Chick',
                'verbose_name_plural': 'Chicks',
                'db_table': 'chicks',
                'ordering': ['created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batchnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('mortalitynumber', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.DateField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, max_length=50, null=True)),
                ('mortality', models.IntegerField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notify_vet', models.BooleanField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chicks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicks_mortality', to='chicks.chicks')),
            ],
            options={
                'verbose_name': 'Mortality',
                'verbose_name_plural': 'Mortality',
                'db_table': 'mortality',
                'ordering': ['created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChicksSold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batchnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('salesnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.DateField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sales', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chicks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicks_chickssold', to='chicks.chicks')),
            ],
            options={
                'verbose_name': 'ChicksSold',
                'verbose_name_plural': 'ChicksSold',
                'db_table': 'chickssold',
                'ordering': ['created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChicksAvailable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batchnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.DateField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breed_chicksavailable', to='breeders.breed')),
            ],
            options={
                'verbose_name': 'ChicksAvailable',
                'verbose_name_plural': 'ChicksAvailable',
                'db_table': 'chicksavailable',
                'ordering': ['created'],
                'managed': True,
            },
        ),
    ]
